#arangodb配置信息
arangodbInfo:
  url:
    'http://10.17.205.190:8529'
  databaseName:
    'graphDB'
  nodeCollectionName:
    'nodes'
  edgeCollectionName:
    invests:
      relations_invest
    guarantees:
      relations_guarantee
    family:
      relations_family
    executes: 
      relations_execute

#ITCode2->ITName
dictionaryServer:
  host: 
    10.10.15.129
    #10.10.15.137
  port:
    #8009
    8010
  path:
    #/lookup
  
#设置查询 server的超时时间
lookupTimeout: 
  30000                                         #超时设置150s
  
#设置每次预热path的间隔时间
sleepTime:
  100

#设置加入预热的path条件
warmUp_Condition:
  queryCost:
    2000                                        #查询arangodb所需时间
  queryRecords:
    200                                        #查询arangodb返回记录数

#主动预热path的redis地址
warmUp_RedisInfo:
  url_0:
    redis://:finchina@10.15.97.135:6679/0       #存放ITCode         
  url_1:
    redis://:finchina@10.15.97.135:6679/9       #存放paths
  TTL:
    86400
  switch:
    'off'
    #'on'
    
#设置cache的信息
NodeCache:
  stdTTL: 
    21600000
  # checkperiod: 
  #   600
  # useClones: 
  #   false
  redisUrl:                                     #存放paths cache
    redis://:finchina@10.15.97.135:6679/11      #注意：需指定一个独立使用的db, 清空缓存时需要清空db中的所有内容
  autoFlushCache:                               #程序重启是否清空缓存
    'true'
    #'fasle'
  switch:
    'off'
    #'on'

#redis存储数据的keyName
redisKeyName:
  timestamp:                                    #记录读取ITCode2的timestamp
    tsp_ITCode
  allITCodes:                                   #记录所有的ITCode2
    ITCodes_all 
  warmUpITCodes:                                #记录预热数据的ITCode2
    ITCodes_warmUp

#设置各个路径的查询深度, 数据预热使用
pathDepth:
  DIDepth:
    2                                           #直接投资关系路径深度
  DIBDepth: 
    2                                           #直接被投资关系路径深度
  IVDepth:
    6                                           #直接投资关系路径深度
  IVBDepth: 
    6                                           #直接被投资关系路径深度
  FUDepth:
    3                                           #全部路径深度
  DIDepth:
    3                                           #单个企业直接投资关系路径深度
  DIBDepth:
    3                                           #单个企业直接被投资关系路径深度
  CIVDepth:                                     
    4                                           #共同投资关系路径深度
  CIVBDepth:
    4                                           #共同被投资关系路径深度
  GTDepth:
    5                                           #担保关系路径深度
  GTBDepth:
    5                                           #被担保关系路径深度

#默认请求时的参数, 数据预热使用
defaultQueryParams:
  relation:
    invests
  returnNoCodeNodes:                            #是否返回无机构代码的机构
    true
  returnBranches:                               #是否返回分支机构
    false
  surStatus:
    1
  
#定时触发主动查询需要预热的path数据
schedule:
  hour:
    12
  minute:
    0

#控制任务并发, 加锁机制信息
lockInfo:
  redisUrl:
    - redis://:finchina@10.15.97.135:6679/2
    - redis://:finchina@10.15.97.135:6679/3
  resource:
    - 'locks:lockTimingWarmUpPaths_app'          #为lockTimingWarmUpPaths方法加锁
  TTL:
    #- 600000
    - 21600000                             #加锁时间, 设置6h

#日志相关信息设置
logInfo:
  maxLogSize:
    20480000

#redis发布与订阅信息
redisPubSubInfo:
  clientUrl:
    - redis://:finchina@10.15.97.135:6679       #确保该redis的URL与导入程序的一致(消息发布者)
  channelsName:
    - 'updateDataNews'
  subMessage:
    - 'updateDataOver'